on: [push]

jobs:
  fontbakery:
    runs-on: ubuntu-latest
    name: Check the fonts with fontbakery
    steps:
        - uses: actions/checkout@v2
        - uses: simoncozens/fontbakery-action@v1
        - name: WTF
          run: find /${{ github.workspace }}/
        - uses: actions/upload-artifact@v2
          with:
            name: Fontbakery reports
            path: ${{ github.workspace }}/fontbakery.*
            if-no-files-found: error
