on: [push]

jobs:
  fontbakery:
    runs-on: ubuntu-latest
    name: Check the fonts with fontbakery
    steps:
        - uses: actions/checkout@v2
        - uses: simoncozens/fontbakery-action@v1
        - uses: actions/upload-artifact@v2
          if: always()
          with:
            name: Fontbakery reports
            path: fontbakery.*
